services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: stoneclub
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 194343
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
volumes: { pgdata: {} }
